name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20 # 최신 노드 버전 강제 지정

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # 빌드된 정적 파일 폴더
          repository-name: hanul000/hanul000.github.io # 내 도메인 저장소 경로
          branch: main
          token: ${{ secrets.GH_PAT }} # 깃허브 인증 토큰
